### ISSUE TITLE
Subtracting the wrong value?

### ISSUE THREAD

**Issue by MosheLichman** [blei-lab/zero-inflated-embedding#1]
https://github.com/blei-lab/zero-inflated-embedding/blob/5a67a49ecbf19f10a6448da7fc54cecdd79015af/graph_builder.py#L139

For computing the alpha_sum value you are using the alpha_weighted. That means that when you reduce the selected alpha to create the context for a specific item 'j' you shouldn't you subtract alpha_weighted and not alpha_select? 

I think that right now you are computing the embedding as:
$$\rho_{s_i}^T ( \sum_{j \in c_i} y_{ij} \alpha_j) + (y_{s_i} - 1) \alpha_{s_i} )$$

If I'm correct about this, it won't be an issue for word embedding where the y's are binary but will be in the case of counts data.

**Comment by lipingliulp** [comment]
It is quite possible this is a bug. I will further investigate it and come back to you.

**Comment by lipingliulp** [comment]
Fixed
