### ISSUE TITLE
Use of test ratings when calculating weighted context

### ISSUE THREAD

**Issue by MosheLichman** [blei-lab/zero-inflated-embedding#2]
https://github.com/blei-lab/zero-inflated-embedding/blob/5a67a49ecbf19f10a6448da7fc54cecdd79015af/zie.py#L136

In this line, the test ratings are passed in and used as rates (line 133 in 'construct_model_graph').  These rates are then used to compute the weighted context (line 135 in 'construct_model_graph').  If I'm not mistaken, the same ratings are then used to compute the log probability (line 25 in 'logprob_nonz').  Shouldn't two sets of labels be passed as 'input_label' within the 'evaluate_emb' method, one for the ratings observed at training time (to compute the context) and another set to compute the test log probability?

I only could replicate your simulation results when using the test ratings for computing the weighted context.

**Comment by lipingliulp** [comment]
I don't get why I need two sets of labels. In "evaluate_emb", I fix embedded vectors and use test data, items and labels, to calculate test log prob.

**Comment by lipingliulp** [comment]
Explanation of the test predictive log-likelihood: the embedding models does not give a full probability -- it only models the conditional probability of a target given its context. The model parameters/embedding vectors are estimated via maximization of pseduo-likelihood. When the model is tested on the test data, we also calculate pseduo-likelihood, so the model will assume context items in the test set are known.
